# Generated by Django 4.2 on 2023-04-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
    ]
